services:
  ldio-workbench:
    container_name: public-ldes_ldio-workbench
    image: ldes/ldi-orchestrator:2.2.0-SNAPSHOT
    volumes:
      - ./application.yml:/ldio/application.yml:ro
    ports:
      - 9006:80
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://ldio-workbench/actuator/health"]
  upsertable_app:
    container_name: upsertable_app
    image: stijndenis/upsertable_app:latest
    ports:
      - 5000:5000
    environment:
      OUTPUT_URL: http://host.docker.internal:9090/ngsi-ld/v1/entityOperations/upsert
  postgres:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
  scorpio:
    image: scorpiobroker/all-in-one-runner:java-latest
    environment:
      DBHOST: postgres
      GATEWAY_ENABLECORS_ALLOWALL: true
    ports:
      - "9090:9090"
    depends_on:
      - postgres
